// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhqxhyzIPrGY9s6XNQWgu-DYd57PzfExA',
    appId: '1:617188085479:web:935cc0b54638536617dc42',
    messagingSenderId: '617188085479',
    projectId: 'aayojan-project',
    authDomain: 'aayojan-project.firebaseapp.com',
    storageBucket: 'aayojan-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqINn8hjG4IgbtXGa4oayyAvzx0dY3FUA',
    appId: '1:617188085479:android:c3e4e98859c258ca17dc42',
    messagingSenderId: '617188085479',
    projectId: 'aayojan-project',
    storageBucket: 'aayojan-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlLpTI4KFNQTF4M4_CzVa0Ya4r2-v3Jnw',
    appId: '1:617188085479:ios:0de39c99f3f5a1f217dc42',
    messagingSenderId: '617188085479',
    projectId: 'aayojan-project',
    storageBucket: 'aayojan-project.firebasestorage.app',
    iosBundleId: 'com.aayojan.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlLpTI4KFNQTF4M4_CzVa0Ya4r2-v3Jnw',
    appId: '1:617188085479:ios:0de39c99f3f5a1f217dc42',
    messagingSenderId: '617188085479',
    projectId: 'aayojan-project',
    storageBucket: 'aayojan-project.firebasestorage.app',
    iosBundleId: 'com.aayojan.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhqxhyzIPrGY9s6XNQWgu-DYd57PzfExA',
    appId: '1:617188085479:web:460b7dadb0c453c417dc42',
    messagingSenderId: '617188085479',
    projectId: 'aayojan-project',
    authDomain: 'aayojan-project.firebaseapp.com',
    storageBucket: 'aayojan-project.firebasestorage.app',
  );

}